REDIS:
  CHANNEL: Core
  PASSWORD: ''

SERVER:
  NAME: Default
  GROUP: Survival
  JOINED: "&b[S] &3<player> &7has &ajoined &7to &b<server>&7."
  LEFT: "&b[S] &3<player> &7has &cleft&7 the network."
  SWITCHED: "&b[S] &3<player> &7has &aswitched &7from &b<server> &7to &b<newserver>&7."

COMMAND:
  NO_PERMISSION: "&cYou don't have enough permissions to run this command."
  NO_PLAYER: "&cNo player found."

PUNISHMENT:
  REMOVED: "Removed"
  PERMANENT: "Permanent"
  EXPIRED: "Expired"
  DAY_FORMAT: "Day"
  HOURS_FORMAT: "Hour"
  MINUTE_FORMAT: "Minute"
  SECONDS_FORMAT: "Second"
  BAN_USAGE: "&cUsage: /ban <player> [duration] <reason> [-s]"
  BAN_ALREADY_BANNED: "&cThat player is already banned."
  BAN_TEMPORARY_MESSAGE: "temporarily"
  BAN_PERMANENT_MESSAGE: "permanently"
  BAN_KICK_MESSAGE:
    - ""
    - "&cYour account has been <context> banned CadiaMC Network."
    - ""
    - "&cBanned By: &f<added_by>"
    - "&cDuration: &f<duration>"
    - "&cReason: &f<reason>"
    - ""
    - "&cAppeal at: &fwww.cadiamc.net"
  BAN_PUBLIC_MESSAGE:
    - "&e<banned> &ahas been banned <context> by &c<added_by>&a."
  BAN_SILENT_MESSAGE:
    - "&7[Silent] &e<banned> &ahas been banned <context> by &c<added_by>&a."
  BLACKLIST_USAGE: "Usage: /blacklist <player> <reason> [-s]"
  BLACKLIST_ALREADY_BANNED: "&cThat player is already banned."
  BLACKLIST_KICK_MESSAGE:
    - ""
    - "&cYour account has been blacklisted from CadiaMC Network."
    - ""
    - "&cBanned By: &f<added_by>"
    - "&cDuration: &f<duration>"
    - "&cReason: &f<reason>"
    - ""
    - "&cThis type of punishment cannot be appealed."
  BLACKLIST_PUBLIC_MESSAGE:
    - "&e<banned> &ahas been blacklisted by &c<added_by>&a."
  BLACKLIST_SILENT_MESSAGE:
    - "&7[Silent] &e<banned> &ahas been blacklisted by &c<added_by>&a."
  WARN_USAGE: "&cUsage: /warn <player> <reason> [-s]"
  WARN_MESSAGE:
    - "&cYou have been warned."
    - "&cReason: &f<reason>"
    - "&cDuration: &f7 days."
  WARN_PUBLIC_MESSAGE:
    - "&e<banned> &ahas been warned by &c<added_by>&a."
  WARN_SILENT_MESSAGE:
    - "&7[Silent] &e<banned> &ahas been warned by &c<added_by>&a."
  UNWARN_USAGE: "&cUsage: /unwarn <plaer> <reason> [-s]"
  UNWARN_NO_WARNS_YET: "&cThis player has no warns yet."
  UNWARN_MESSAGE:
    - "&aA warning from your punishment history has been removed."
  UNWARN_PUBLIC_MESSAGE:
    - "&e<banned> &ahas been unwarned by &c<added_by>&a."
  UNWARN_SILENT_MESSAGE:
    - "&7[Silent] &e<banned> &ahas been unwarned by &c<added_by>&a."
  UNMUTE_USAGE: "&cUsage: /unmute <player> <reason> [-s]"
  UNMUTE_NO_WARNS_YET: "&cThis player has no mutes yet."
  UNMUTE_MESSAGE:
    - "&aYou are able to use the chat again."
  UNMUTE_PUBLIC_MESSAGE:
    - "&e<banned> &ahas been unmuted by &c<added_by>&a."
  UNMUTE_SILENT_MESSAGE:
    - "&7[Silent] &e<banned> &ahas been unmuted by &c<added_by>&a."
  UNBAN_USAGE: "&cUsage: /unban <player> <reason> [-s]"
  UNBAN_NO_BANS_YET: "&cThis player has no bans yet."
  UNBAN_PUBLIC_MESSAGE:
    - "&e<banned> &ahas been unbanned by &c<added_by>&a."
  UNBAN_SILENT_MESSAGE:
    - "&7[Oculto] &e<banned> &ahas been unbanned by &c<added_by>&a."
  MUTE_USAGE: "&cUsage: /mute <player> <reason> [-s]"
  MUTE_MESSAGE:
    - "&cYou have been muted"
    - "&cReason: &f<reason>"
    - "&cDuration: &f<duration>."
  MUTE_PUBLIC_MESSAGE:
    - "&e<banned> &ahas been muted by &c<added_by>&a."
  MUTE_SILENT_MESSAGE:
    - "&7[Silent] &e<banned> &ahas been muted by &c<added_by>&a."
  KICK_USAGE: "&cUsage: /kick <player> <reason> [-s]"
  KICK_NO_PLAYER: "&cJugador no encontrado."
  KICK_MESSAGE:
    - ""
    - "&cYou have been kicked from CadiaMC Network."
    - ""
    - "&cKicked By: &f<added_by>"
    - "&cReason: &f<reason>"
    - ""
  KICK_PUBLIC_MESSAGE:
    - "&e<banned> &aha sido silenciado por &c<added_by>&a."
  KICK_SILENT_MESSAGE:
    - "&7[Oculto] &e<banned> &aha sido silenciado por &c<added_by>&a."
  PUNISH_SELECTOR_MENU:
    TITLE: "&cSelect a type of punishment"
    SLOTS: 27
    BUTTONS:
      BAN:
        TITLE: "&eBans"
        MATERIAL: BEDROCK
        DATA: 0
        TYPE: BAN
        LORE:
          - "&e"
  PUNISH_MENU:
    TITLE: "&cPunishments - <total>"
    SLOTS: 27
    BUTTON:
      TITLE: "&e<punishment_type>"
      MATERIAL: DIAMOND
      DATA: 0
      LORE:
        - "&7&m-----------------------"
        - "&eAdded by: &7<banned_by>"
        - "  "
        - "&eDate: &7<date>"
        - "&eReason: &7<reason>"
        - "&7&m-----------------------"
      EXPIRED_LORE:
        - "&ePunishment Expired."
        - "&7&m-----------------------"
      REMOVED_LORE:
        - "&eRemoved by: &7<removed_by>"
        - "&eDate: &7<removed_date>"
        - "&eReason: &7<removed_reason>"
        - "&7&m-----------------------"
ALTS:
  USAGE:
    - "&cUsage: /alts <player>"
  ALT_FORMAT: "&7- &e<alt_name> &7(<online>&7) &7(<banned>&7) &7(<muted>&7)"
  ALT_BANNED_FORMAT: "&cBanned"
  ALT_NOT_BANNED_FORMAT: "No Punishments"
  ALT_MUTED_FORMAT: "&cMuted"
  ALT_NOT_MUTED_FORMAT: "No Mutes"
  ALT_ONLINE: "&aOnline"
  ALT_OFFLINE: "&cOffline"
  NO_ALTS: "&cThis player has no alts yet."
  ALT_MESSAGE:
    - ""
    - "&cAlt of players &e<player>"
    - ""
    - "<alt_format>"
    - ""
WIPE_PUNISHMENTS:
  USAGE:
    - "&cUsage: /wipepunishments <ban|blacklist|mute|warn|kick>"
  INVALID_TYPE: "&cInvalid punishment type."
  WIPED: "&aA total of &e<total> &epunishments."

STAFF_ROLLBACK:
  USAGE:
    - "&cUsage: /staffrollback <player> <time>"
  CLEARED_PUNISHMENTS: "&aA total of &e<total> &epunishments have been removed."

FLY:
  ENABLED: "&aFly enabled."
  DISABLED: "&cFly disabled."

CHAT:
  DONOR_CHAT: "&7[DC] &f(<server>) <player>&7: &f<message>"
  STAFF_CHAT: "&b[S] &f(<server>) <player>&7: &f<message>"
  ADMIN_CHAT: "&c[AC] &f(<server>) <player>&7: &f<message>"

DONATOR_CHAT:
  DISABLED: "&cSuccessfully disabled donatorchat."
  ENABLED: "&aSuccessfully enabled donatorchat."

ADMIN_CHAT:
  DISABLED: "&cSuccessfully disabled admin chat."
  ENABLED: "&aSuccessfully enabled adminchat."

STAFF_CHAT:
  DISABLED: "&cSuccessfully disabled staffchat."
  ENABLED: "&aSuccessfully enabled staffchat."

FREEZE:
  USAGE:
    - "&cUsage: /freeze <player>"
  ALLOWED_COMMANDS:
    - "/message"
    - "/msg"
    - "/tell"
    - "/m"
  FREEZE_MESSAGE:
    - "&7"
    - "&c&lYOU HAVE BEEN FROZEN."
    - ""
    - "&7Follow staff instructions."
    - "&cLogging out: PERMANENT BAN."
    - ""
  UNFREEZE_MESSAGE:
    - "&7"
    - "&c&lYOU HAVE BEEN UN-FROZEN."
    - "&7"
  LOGGED_OUT:
    - "&7(Freeze) &f<player> &chas logged out while frozen."
  FREEZE_MESSAGE_STAFF: "&7(Freeze) &f<player> &bhas been frozen by &f<staff>&b."
  UNFREEZE_MESSAGE_STAFF: "&7(Freeze) &f<player> &bhas been unfrozen by &f<staff>&b."
  MESSAGE_WHEN:
    - "00:30"
    - "01:00"
    - "01:30"
    - "02:00"
    - "02:30"
    - "03:00"
    - "03:30"
    - "04:00"
    - "04:30"
    - "05:00"
    - "06:00"
    - "07:00"
    - "08:00"
    - "09:00"
    - "10:00"
    - "20:00"
    - "30:00"
    - "40:00"
    - "50:00"
  FREEZE_TIMER_MESSAGE: "&7(Freeze) &f<player> &bis frozen. &7(Timer: <time>)"

VANISH:
  ENABLED: "&aVanish successfully enabled."
  DISABLED: "&cVanish successfully disabled."

STAFFMODE:
  ENABLED: "&aStaffMode successfully enabled."
  DISABLED: "&cStaffMode successfully disabled."