REDIS:
  IP: "localhost"
  PORT: 6379
  PASSWORD: ""
  CHANNEL: "StaffCore"

MONGO:
  IP: "localhost"
  PORT: 27017
  USER: "root"
  PASSWORD: ""
  DATABASE: "StaffCore"

SERVER:
  NAME: Default
  GROUP: Survival

PUNISHMENT:
  PUNISH_SELECTOR_MENU:
    TITLE: "&cSelect a type of punishment"
    SLOTS: 27
    BUTTONS:
      BAN:
        TITLE: "&eBans"
        MATERIAL: BEDROCK
        DATA: 0
        TYPE: BAN
        LORE:
          - "&e"
  PUNISH_MENU:
    TITLE: "&cPunishments - <total>"
    SLOTS: 27
    BUTTON:
      TITLE: "&e<punishment_type>"
      MATERIAL: DIAMOND
      DATA: 0
      LORE:
        - "&7&m-----------------------"
        - "&eAdded by: &7<banned_by>"
        - "  "
        - "&eDate: &7<date>"
        - "&eReason: &7<reason>"
        - "&7&m-----------------------"
      EXPIRED_LORE:
        - "&ePunishment Expired."
        - "&7&m-----------------------"
      REMOVED_LORE:
        - "&eRemoved by: &7<removed_by>"
        - "&eDate: &7<removed_date>"
        - "&eReason: &7<removed_reason>"
        - "&7&m-----------------------"
