name: StaffCore
main: online.nasgar.staffcore.StaffCore
version: 1.0
author: Fckml

api-version: 1.13

libraries:
  - org.mongodb:mongodb-driver:3.12.11
  - redis.clients:jedis:4.3.1
  - org.apache.commons:commons-lang3:3.12.0
  - org.projectlombok:lombok:1.18.24